{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mikoto.pixiv",
    "module": "pixiv-api",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pixiv-api-1.3.2-plain.jar",
          "url": "pixiv-api-1.3.2-plain.jar",
          "size": 27360,
          "sha512": "ecdab039c8b9c18e8f3d4053d871e88195e64c353ee9a648a1a515f531ad2d2551a4b10ea32bd5634ae1da42b4dc8a39df1d80f254cc2dcdca963d9c2a5aac7d",
          "sha256": "7590d72a182dbb266b96d105ca55895e065d5e07ed843a94eeed16a89d473e13",
          "sha1": "73b050242fe4b89f7b7b82950a2cb5bca3373f03",
          "md5": "4e4d2f37dc436c6ac01b7db2f21b9b1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pixiv-api-1.3.2-plain.jar",
          "url": "pixiv-api-1.3.2-plain.jar",
          "size": 27360,
          "sha512": "ecdab039c8b9c18e8f3d4053d871e88195e64c353ee9a648a1a515f531ad2d2551a4b10ea32bd5634ae1da42b4dc8a39df1d80f254cc2dcdca963d9c2a5aac7d",
          "sha256": "7590d72a182dbb266b96d105ca55895e065d5e07ed843a94eeed16a89d473e13",
          "sha1": "73b050242fe4b89f7b7b82950a2cb5bca3373f03",
          "md5": "4e4d2f37dc436c6ac01b7db2f21b9b1e"
        }
      ]
    }
  ]
}
