{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mikoto.pixiv",
    "module": "pixiv-core",
    "version": "1.4.4-snapshot-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pixiv-core-1.4.4-snapshot-1-plain.jar",
          "url": "pixiv-core-1.4.4-snapshot-1-plain.jar",
          "size": 48361,
          "sha512": "af63b04b4af173e841927aac077947997fc7ad7c22f918a9c7a676619943bd7abbcde8161c85bde11768913eb0e142da1f44917c0f0563e7f22c4efbef629660",
          "sha256": "07d1f3fd2cce3083bc8e9f6bdb85d7a2654c758eed1beb53ca5916fb74a3eda3",
          "sha1": "768f0685e01e640ff2bc30c95ce93a142ccdb270",
          "md5": "e9ad269bd65454afb818751e7c0bad6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "2.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "pixiv-core-1.4.4-snapshot-1-plain.jar",
          "url": "pixiv-core-1.4.4-snapshot-1-plain.jar",
          "size": 48361,
          "sha512": "af63b04b4af173e841927aac077947997fc7ad7c22f918a9c7a676619943bd7abbcde8161c85bde11768913eb0e142da1f44917c0f0563e7f22c4efbef629660",
          "sha256": "07d1f3fd2cce3083bc8e9f6bdb85d7a2654c758eed1beb53ca5916fb74a3eda3",
          "sha1": "768f0685e01e640ff2bc30c95ce93a142ccdb270",
          "md5": "e9ad269bd65454afb818751e7c0bad6d"
        }
      ]
    }
  ]
}
