{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mikoto.pixiv",
    "module": "pixiv-forward-connector",
    "version": "1.1.2-snapshot-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pixiv-forward-connector-1.1.2-snapshot-2-plain.jar",
          "url": "pixiv-forward-connector-1.1.2-snapshot-2-plain.jar",
          "size": 7851,
          "sha512": "4735de4ead80c9410f4c0fa2adcf62642ba5b98a834fcc05cd32143ff8ea94dca10ed677d3a25f633b3b4687fcd8058ad8a210f3e2d03fed4b525433f15c0ce7",
          "sha256": "98d2c6b0416dc87876868a3ed64ca54a571680b67fea5a7ff59e079f6a66a36a",
          "sha1": "75f10fed6987e028d5395eae16744c7bdaa6324e",
          "md5": "7d45f40d35ce054ed972ea8c4a2c0bca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pixiv-forward-connector-1.1.2-snapshot-2-plain.jar",
          "url": "pixiv-forward-connector-1.1.2-snapshot-2-plain.jar",
          "size": 7851,
          "sha512": "4735de4ead80c9410f4c0fa2adcf62642ba5b98a834fcc05cd32143ff8ea94dca10ed677d3a25f633b3b4687fcd8058ad8a210f3e2d03fed4b525433f15c0ce7",
          "sha256": "98d2c6b0416dc87876868a3ed64ca54a571680b67fea5a7ff59e079f6a66a36a",
          "sha1": "75f10fed6987e028d5395eae16744c7bdaa6324e",
          "md5": "7d45f40d35ce054ed972ea8c4a2c0bca"
        }
      ]
    }
  ]
}
