{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mikoto.pixiv",
    "module": "pixiv-core",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pixiv-core-1.4.3-plain.jar",
          "url": "pixiv-core-1.4.3-plain.jar",
          "size": 47017,
          "sha512": "5b990fe0d096609aa93cfba47543e95508a610ab9f7ea6e58562679011811444a71f7a3ddc35c81d9ae92ab28ac31c1510a0951e7f326d3c271124b059fdd7cf",
          "sha256": "0f9ef9104b96cbfbf2df0657126a761c94dbb46b8f49fddd9131d068cc4ceb53",
          "sha1": "2effdad54261def50e96310af637bc487949c335",
          "md5": "5f067f2f42109fbf84d79c54f2dfd764"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "2.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "pixiv-core-1.4.3-plain.jar",
          "url": "pixiv-core-1.4.3-plain.jar",
          "size": 47017,
          "sha512": "5b990fe0d096609aa93cfba47543e95508a610ab9f7ea6e58562679011811444a71f7a3ddc35c81d9ae92ab28ac31c1510a0951e7f326d3c271124b059fdd7cf",
          "sha256": "0f9ef9104b96cbfbf2df0657126a761c94dbb46b8f49fddd9131d068cc4ceb53",
          "sha1": "2effdad54261def50e96310af637bc487949c335",
          "md5": "5f067f2f42109fbf84d79c54f2dfd764"
        }
      ]
    }
  ]
}
