{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mikoto.pixiv",
    "module": "pixiv-core",
    "version": "1.4.3-snapshot-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pixiv-core-1.4.3-snapshot-1-plain.jar",
          "url": "pixiv-core-1.4.3-snapshot-1-plain.jar",
          "size": 40869,
          "sha512": "777771f6a2cb0ad9787fbc963e9ae077277e820e0f94cbe96b734150eae7d8e33775adb6944d59b642c2f3d4cecbf9359271a5a7d302afc6cf879150aef681ab",
          "sha256": "94d0671aec3b222c2783cae2460dc139148beb927a973578a366d8d4ea0a4fef",
          "sha1": "5fd2dc1fd09e5b34a1de26443a2175b5e9e7b3a2",
          "md5": "22af9b68142a1e902f7d151129556502"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "2.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "pixiv-core-1.4.3-snapshot-1-plain.jar",
          "url": "pixiv-core-1.4.3-snapshot-1-plain.jar",
          "size": 40869,
          "sha512": "777771f6a2cb0ad9787fbc963e9ae077277e820e0f94cbe96b734150eae7d8e33775adb6944d59b642c2f3d4cecbf9359271a5a7d302afc6cf879150aef681ab",
          "sha256": "94d0671aec3b222c2783cae2460dc139148beb927a973578a366d8d4ea0a4fef",
          "sha1": "5fd2dc1fd09e5b34a1de26443a2175b5e9e7b3a2",
          "md5": "22af9b68142a1e902f7d151129556502"
        }
      ]
    }
  ]
}
