{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mikoto.pixiv",
    "module": "pixiv-core",
    "version": "1.4.3-snapshot-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pixiv-core-1.4.3-snapshot-1-plain.jar",
          "url": "pixiv-core-1.4.3-snapshot-1-plain.jar",
          "size": 38480,
          "sha512": "6822884ba7b346664982fa5c551e1b9cec4b86cfa87932e973d1dd25d4be76da5972127e99aa1a4cddb92bf59e62a707180ef7f52cfd72e8603510050a5b934a",
          "sha256": "4c926874c42d0a7c8b112fc209f1f0b19274bf2da9c614163eb2695d0cad294e",
          "sha1": "acbb3cbecca60bfd188f566ddfd7a6fad623bfda",
          "md5": "921f5e07504123d16dd82288b63d3f30"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "2.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "pixiv-core-1.4.3-snapshot-1-plain.jar",
          "url": "pixiv-core-1.4.3-snapshot-1-plain.jar",
          "size": 38480,
          "sha512": "6822884ba7b346664982fa5c551e1b9cec4b86cfa87932e973d1dd25d4be76da5972127e99aa1a4cddb92bf59e62a707180ef7f52cfd72e8603510050a5b934a",
          "sha256": "4c926874c42d0a7c8b112fc209f1f0b19274bf2da9c614163eb2695d0cad294e",
          "sha1": "acbb3cbecca60bfd188f566ddfd7a6fad623bfda",
          "md5": "921f5e07504123d16dd82288b63d3f30"
        }
      ]
    }
  ]
}
